config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :book_authors
  resources :books
  resources :genres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book, touch: true
  belongs_to :author, touch: true
end

app/controllers/book_authors_controller.rb
class BookAuthorsController < ApplicationController
  before_action :set_book_author, only: %i[ show edit update destroy ]

  # GET /book_authors or /book_authors.json
  def index
    @book_authors = BookAuthor.all
  end

  # GET /book_authors/1 or /book_authors/1.json
  def show
  end

  # GET /book_authors/new
  def new
    @book_author = BookAuthor.new
  end

  # GET /book_authors/1/edit
  def edit
  end

  # POST /book_authors or /book_authors.json
  def create
    @book_author = BookAuthor.new(book_author_params)

    respond_to do |format|
      if @book_author.save
        format.html { redirect_to book_author_url(@book_author), notice: "Book author was successfully created." }
        format.json { render :show, status: :created, location: @book_author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_authors/1 or /book_authors/1.json
  def update
    respond_to do |format|
      if @book_author.update(book_author_params)
        format.html { redirect_to book_author_url(@book_author), notice: "Book author was successfully updated." }
        format.json { render :show, status: :ok, location: @book_author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_authors/1 or /book_authors/1.json
  def destroy
    @book_author.destroy

    respond_to do |format|
      format.html { redirect_to book_authors_url, notice: "Book author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_author
      @book_author = BookAuthor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_author_params
      params.require(:book_author).permit(:book_id, :author_id)
    end
end

app/helpers/book_authors_helper.rb
module BookAuthorsHelper
end

app/views/book_authors/_book_author.html.erb
<div id="<%= dom_id book_author %>">
  <p>
    <strong>Book:</strong>
    <%= book_author.book_id %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book_author.author_id %>
  </p>

</div>

app/views/book_authors/_form.html.erb
<%= form_with(model: book_author) do |form| %>
  <% if book_author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book_author.errors.count, "error") %> prohibited this book_author from being saved:</h2>

      <ul>
        <% book_author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.text_field :book_id %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/book_authors/edit.html.erb
<h1>Editing book author</h1>

<%= render "form", book_author: @book_author %>

<br>

<div>
  <%= link_to "Show this book author", @book_author %> |
  <%= link_to "Back to book authors", book_authors_path %>
</div>

app/views/book_authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Book authors</h1>

<div id="book_authors">
  <% @book_authors.each do |book_author| %>
    <%= render book_author %>
    <p>
      <%= link_to "Show this book author", book_author %>
    </p>
  <% end %>
</div>

<%= link_to "New book author", new_book_author_path %>

app/views/book_authors/new.html.erb
<h1>New book author</h1>

<%= render "form", book_author: @book_author %>

<br>

<div>
  <%= link_to "Back to book authors", book_authors_path %>
</div>

app/views/book_authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_author %>

<div>
  <%= link_to "Edit this book author", edit_book_author_path(@book_author) %> |
  <%= link_to "Back to book authors", book_authors_path %>

  <%= button_to "Destroy this book author", @book_author, method: :delete %>
</div>